# Generated by Django 4.2.8 on 2024-04-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('product', '0002_alter_product_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy'),
        ),
    ]
