# Generated by Django 4.2.8 on 2024-04-10 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('bmi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.DecimalField(decimal_places=2, max_digits=19)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=19)),
                ('classification', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bmi',
            },
        ),
        migrations.CreateModel(
            name='DietConsultation',
            fields=[
                ('diet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diet', models.CharField(max_length=255)),
                ('diet_category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'diet',
            },
        ),
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'family_profile',
            },
        ),
        migrations.CreateModel(
            name='SetReminder',
            fields=[
                ('reminder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medication_time', models.DateTimeField()),
                ('dosage', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminder',
            },
        ),
    ]
